# Generated by Django 3.0.7 on 2020-06-18 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoesapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe',
            old_name='branch_name',
            new_name='brand_name',
        ),
    ]
